#!/bin/bash
#SBATCH -A project_2010972
#SBATCH --job-name=primer_dev
#SBATCH -o /projappl/project_2010972/logs/primer_dev.log
#SBATCH -p gpumedium
#SBATCH --mail-type=BEGIN,END,FAIL,TIME_LIMIT_90
#SBATCH --mail-user=jue.hou@helsinki.fi
#SBATCH --nodes=1
#SBATCH -c 48
#SBATCH -t 36:00:00
#SBATCH --mem=256G
#SBATCH --gres=gpu:a100:4

module purge
module load pytorch/2.1

python3 trainer.py --multi_gpu --mode test --num_worker 10 --adafactor \
    --model_path /scratch/project_2010972/primer_dev \
    --primer_path /scratch/project_2010972/pretrained_model/PRIMER_multinews  \
    --data_path /scratch/project_2010972/datasets \
    --dataset_name ecdc_test_data_summary_text_5_weeks_22sep 